package GUI;

import camadaDados.RepositorioVeiculo;
import camadaDados.Veiculo;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Buscar.java
 *
 * Created on 14/06/2012, 16:32:54
 */
/**
 *
 * @author dca
 */
public class Buscar extends javax.swing.JFrame {

    private VeiculoViewer home;
    private RepositorioVeiculo veiculos;
    private ImageIcon foto;
    /** Creates new form Buscar */
    public Buscar(VeiculoViewer home, RepositorioVeiculo veiculos) {
        this.home = home;
        this.veiculos = veiculos;
        initComponents();
        fotoButton.setEnabled(false);
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        velocidadeLabel = new javax.swing.JLabel();
        capacidadeLabel = new javax.swing.JLabel();
        modeloLabel = new javax.swing.JLabel();
        autonomiaLabel = new javax.swing.JLabel();
        chassiLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        fotoButton = new javax.swing.JButton();
        chassiTextField = new javax.swing.JTextField();
        modeloTextField = new javax.swing.JTextField();
        capacidadeTextField = new javax.swing.JTextField();
        velocidadeTextField = new javax.swing.JTextField();
        autonomiaTextField = new javax.swing.JTextField();
        tipoTextField = new javax.swing.JTextField();
        buscaLabel = new javax.swing.JLabel();
        buscaTextField = new javax.swing.JTextField();
        buscaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Veículo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(385, 280));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fechar(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        velocidadeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        velocidadeLabel.setText("Velocidade:");
        jPanel1.add(velocidadeLabel);
        velocidadeLabel.setBounds(200, 80, 70, 20);

        capacidadeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        capacidadeLabel.setText("Capacidade:");
        jPanel1.add(capacidadeLabel);
        capacidadeLabel.setBounds(20, 80, 70, 20);

        modeloLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        modeloLabel.setText("Modelo:");
        jPanel1.add(modeloLabel);
        modeloLabel.setBounds(20, 50, 50, 20);

        autonomiaLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        autonomiaLabel.setText("Autonomia:");
        jPanel1.add(autonomiaLabel);
        autonomiaLabel.setBounds(20, 110, 70, 20);

        chassiLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chassiLabel.setText("Chassi:");
        jPanel1.add(chassiLabel);
        chassiLabel.setBounds(20, 20, 40, 20);

        tipoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tipoLabel.setText("Tipo:");
        jPanel1.add(tipoLabel);
        tipoLabel.setBounds(170, 110, 27, 20);

        fotoButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fotoButton.setText("Ver Foto");
        fotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fotoButton);
        fotoButton.setBounds(20, 140, 90, 23);

        chassiTextField.setEditable(false);
        jPanel1.add(chassiTextField);
        chassiTextField.setBounds(70, 20, 270, 20);

        modeloTextField.setEditable(false);
        jPanel1.add(modeloTextField);
        modeloTextField.setBounds(70, 50, 270, 20);

        capacidadeTextField.setEditable(false);
        jPanel1.add(capacidadeTextField);
        capacidadeTextField.setBounds(100, 80, 90, 20);

        velocidadeTextField.setEditable(false);
        jPanel1.add(velocidadeTextField);
        velocidadeTextField.setBounds(270, 80, 70, 20);

        autonomiaTextField.setEditable(false);
        jPanel1.add(autonomiaTextField);
        autonomiaTextField.setBounds(100, 110, 60, 20);

        tipoTextField.setEditable(false);
        jPanel1.add(tipoTextField);
        tipoTextField.setBounds(210, 110, 130, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 360, 180);

        buscaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buscaLabel.setText(" Chassi:");
        getContentPane().add(buscaLabel);
        buscaLabel.setBounds(10, 30, 50, 20);

        buscaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarEnter(evt);
            }
        });
        getContentPane().add(buscaTextField);
        buscaTextField.setBounds(60, 30, 230, 20);

        buscaButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buscaButton.setText("Buscar");
        buscaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscar(evt);
            }
        });
        getContentPane().add(buscaButton);
        buscaButton.setBounds(290, 30, 80, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar
        home.setVisible(true);
    }//GEN-LAST:event_fechar

    private void buscar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscar
        try{
            Veiculo retornado = veiculos.buscarVeiculo(Integer.parseInt(buscaTextField.getText()));
            chassiTextField.setText(""+retornado.getChassi());
            modeloTextField.setText(retornado.getModelo());
            capacidadeTextField.setText(""+retornado.getCapacidade());
            velocidadeTextField.setText(""+retornado.getVelocidade());
            autonomiaTextField.setText(""+retornado.getAutonomia());
            tipoTextField.setText(retornado.getTipo());
            foto = retornado.getImagem();
            fotoButton.setEnabled(true);
        }
        catch(Exception e){
            if(e.getMessage()!=null){
                String mensagem = "<html><font size = 4><b>"+e.getMessage() +"</html></b>"; 
                JOptionPane.showMessageDialog(null, mensagem , "Erro na busca", JOptionPane.INFORMATION_MESSAGE);
            }
            else
                e.printStackTrace();
        }
    }//GEN-LAST:event_buscar

    private void fotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoButtonActionPerformed
        JLabel label = new JLabel(foto);
        label.setSize(foto.getIconWidth(), foto.getIconHeight());
        JFrame frame = new JFrame();
        frame.add(label);
        frame.setSize(label.getSize());
        frame.setVisible(true);
    }//GEN-LAST:event_fotoButtonActionPerformed

    private void buscarEnter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarEnter
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            buscar(null);
        }
    }//GEN-LAST:event_buscarEnter

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Buscar(null,null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autonomiaLabel;
    private javax.swing.JTextField autonomiaTextField;
    private javax.swing.JButton buscaButton;
    private javax.swing.JLabel buscaLabel;
    private javax.swing.JTextField buscaTextField;
    private javax.swing.JLabel capacidadeLabel;
    private javax.swing.JTextField capacidadeTextField;
    private javax.swing.JLabel chassiLabel;
    private javax.swing.JTextField chassiTextField;
    private javax.swing.JButton fotoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modeloLabel;
    private javax.swing.JTextField modeloTextField;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JTextField tipoTextField;
    private javax.swing.JLabel velocidadeLabel;
    private javax.swing.JTextField velocidadeTextField;
    // End of variables declaration//GEN-END:variables
}
