/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cadastrar.java
 *
 * Created on 14/06/2012, 17:52:02
 */
package GUI;

import camadaDados.RepositorioVeiculo;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.filechooser.*;
/**
 *
 * @author dca
 */
public class Cadastrar extends javax.swing.JFrame {

    private VeiculoViewer home;
    /** Creates new form Cadastrar */
    private RepositorioVeiculo veiculos;
    File fotos;
    
    public Cadastrar(VeiculoViewer home, RepositorioVeiculo veiculos){
        this.home = home;
        this.veiculos =  veiculos;
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        velocidadeLabel = new javax.swing.JLabel();
        capacidadeLabel = new javax.swing.JLabel();
        modeloLabel = new javax.swing.JLabel();
        autonomiaLabel = new javax.swing.JLabel();
        chassiLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        fotoButton = new javax.swing.JButton();
        chassiTextField = new javax.swing.JTextField();
        modeloTextField = new javax.swing.JTextField();
        capacidadeTextField = new javax.swing.JTextField();
        velocidadeTextField = new javax.swing.JTextField();
        autonomiaTextField = new javax.swing.JTextField();
        tipoTextField = new javax.swing.JTextField();
        cadastrarButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        arquivoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Veículo");
        setMinimumSize(new java.awt.Dimension(385, 275));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fechar(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        velocidadeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        velocidadeLabel.setText("Velocidade:");
        jPanel1.add(velocidadeLabel);
        velocidadeLabel.setBounds(200, 80, 70, 20);

        capacidadeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        capacidadeLabel.setText("Capacidade:");
        jPanel1.add(capacidadeLabel);
        capacidadeLabel.setBounds(20, 80, 70, 20);

        modeloLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        modeloLabel.setText("Modelo:");
        jPanel1.add(modeloLabel);
        modeloLabel.setBounds(20, 50, 50, 20);

        autonomiaLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        autonomiaLabel.setText("Autonomia:");
        jPanel1.add(autonomiaLabel);
        autonomiaLabel.setBounds(20, 110, 70, 20);

        chassiLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chassiLabel.setText("Chassi:");
        jPanel1.add(chassiLabel);
        chassiLabel.setBounds(20, 20, 40, 20);

        tipoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tipoLabel.setText("Tipo:");
        jPanel1.add(tipoLabel);
        tipoLabel.setBounds(170, 110, 27, 20);

        fotoButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fotoButton.setText("Foto");
        fotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fotoButton);
        fotoButton.setBounds(20, 140, 90, 23);
        jPanel1.add(chassiTextField);
        chassiTextField.setBounds(70, 20, 270, 20);
        jPanel1.add(modeloTextField);
        modeloTextField.setBounds(70, 50, 270, 20);
        jPanel1.add(capacidadeTextField);
        capacidadeTextField.setBounds(100, 80, 90, 20);
        jPanel1.add(velocidadeTextField);
        velocidadeTextField.setBounds(270, 80, 70, 20);
        jPanel1.add(autonomiaTextField);
        autonomiaTextField.setBounds(100, 110, 60, 20);
        jPanel1.add(tipoTextField);
        tipoTextField.setBounds(210, 110, 130, 20);

        cadastrarButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrar(evt);
            }
        });
        jPanel1.add(cadastrarButton);
        cadastrarButton.setBounds(160, 180, 90, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelar(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(260, 180, 90, 23);

        arquivoTextField.setEnabled(false);
        jPanel1.add(arquivoTextField);
        arquivoTextField.setBounds(120, 140, 220, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 360, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelar
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelar

    private void fechar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar
        home.setVisible(true);
    }//GEN-LAST:event_fechar

    private void cadastrar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrar
        String mensagem;
        try {
            veiculos.inserirVeiculo(Integer.parseInt(chassiTextField.getText()), 
                                    modeloTextField.getText(),
                                    Integer.parseInt(capacidadeTextField.getText()),
                                    Integer.parseInt(velocidadeTextField.getText()),
                                    Integer.parseInt(autonomiaTextField.getText()),
                                    tipoTextField.getText(), arquivoTextField.getText());
            mensagem = "<html><font size = 4><b>Veículo cadastrado com sucesso!</html></b>"; 
            JOptionPane.showMessageDialog(null, mensagem , "Cadastro concluído", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception e){
            e.printStackTrace();
            //mensagem = "<html><font size = 4><b>"+e.getMessage()+"</html></b>"; 
            //JOptionPane.showMessageDialog(null, mensagem , "Falha no cadastro", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cadastrar

    private void fotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoButtonActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "JPG & GIF Images", "jpg", "gif");
        jFileChooser1.setFileFilter(filter);
        int ret = jFileChooser1.showOpenDialog(null);
        if (ret == jFileChooser1.APPROVE_OPTION)  fotos = jFileChooser1.getSelectedFile();
        arquivoTextField.setText(fotos.getAbsolutePath());
    }//GEN-LAST:event_fotoButtonActionPerformed

    private void limparCampos(){
        chassiTextField.setText(null);
        modeloTextField.setText(null);
        capacidadeTextField.setText(null);
        velocidadeTextField.setText(null);
        autonomiaTextField.setText(null);
        tipoTextField.setText(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Cadastrar(null, null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arquivoTextField;
    private javax.swing.JLabel autonomiaLabel;
    private javax.swing.JTextField autonomiaTextField;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JLabel capacidadeLabel;
    private javax.swing.JTextField capacidadeTextField;
    private javax.swing.JLabel chassiLabel;
    private javax.swing.JTextField chassiTextField;
    private javax.swing.JButton fotoButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modeloLabel;
    private javax.swing.JTextField modeloTextField;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JTextField tipoTextField;
    private javax.swing.JLabel velocidadeLabel;
    private javax.swing.JTextField velocidadeTextField;
    // End of variables declaration//GEN-END:variables
}
