package GUI;

import camadaDados.RepositorioVeiculo;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Remover.java
 *
 * Created on 14/06/2012, 17:16:02
 */
/**
 *
 * @author dca
 */
public class Remover extends javax.swing.JFrame {

    private VeiculoViewer home;
    private RepositorioVeiculo veiculos;
    /** Creates new form Remover */
    public Remover(VeiculoViewer home, RepositorioVeiculo veiculos) {
        this.home = home;
        this.veiculos = veiculos;
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscaLabel = new javax.swing.JLabel();
        buscaTextField = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remover Veículo");
        setMinimumSize(new java.awt.Dimension(410, 100));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fechar(evt);
            }
        });
        getContentPane().setLayout(null);

        buscaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buscaLabel.setText(" Chassi:");
        getContentPane().add(buscaLabel);
        buscaLabel.setBounds(10, 20, 50, 20);

        buscaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                removerEnter(evt);
            }
        });
        getContentPane().add(buscaTextField);
        buscaTextField.setBounds(60, 20, 230, 20);

        removeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        removeButton.setText("Remover");
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remover(evt);
            }
        });
        getContentPane().add(removeButton);
        removeButton.setBounds(290, 20, 90, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar
        home.setVisible(true);
    }//GEN-LAST:event_fechar

    private void remover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remover
        String mensagem = "<html><font size = 4><b>Remover Veículo?</html></b>";  
        int resposta = JOptionPane.showConfirmDialog(null, mensagem , "Remover", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE );
        if(resposta == 0){
            try {
                veiculos.removerVeiculo(Integer.parseInt(buscaTextField.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(Remover.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Remover.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
    }//GEN-LAST:event_remover

    private void removerEnter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_removerEnter
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            remover(null);
        }
    }//GEN-LAST:event_removerEnter

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Remover(null,null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscaLabel;
    private javax.swing.JTextField buscaTextField;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
