/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TesteImg.java
 *
 * Created on 16/06/2012, 19:38:46
 */
package GUI;

import camadaDados.RepositorioVeiculo;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author rsvc
 */
public class TesteImg extends javax.swing.JFrame {

    /** Creates new form TesteImg */
    public TesteImg() {
        
        initComponents();
        
    }
    
     public JLabel getLabel(){
        return this.jLabel1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException, ClassNotFoundException {
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                try {
                    RepositorioVeiculo r =  new RepositorioVeiculo();
                    TesteImg home = new TesteImg();
                    try {
                        ImageIcon a = r.buscarVeiculo(90).getImagem();
                         home.getLabel().setIcon(a);
                    } catch (SQLException ex) {
                        Logger.getLogger(TesteImg.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(TesteImg.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (Exception ex) {
                        Logger.getLogger(TesteImg.class.getName()).log(Level.SEVERE, null, ex);
                    }
                     home.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TesteImg.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TesteImg.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
