package GUI;

import camadaDados.RepositorioVeiculo;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VeiculoViewer.java
 *
 * Created on 14/06/2012, 16:19:22
 */
/**
 *
 * @author dca
 */
public class VeiculoViewer extends javax.swing.JFrame {

    private RepositorioVeiculo veiculos;
    /** Creates new form VeiculoViewer */
    public VeiculoViewer() {
        try{
            initComponents();
            veiculos = new RepositorioVeiculo();
            setLocationRelativeTo(null);
        }
        catch(Exception e){
            String mensagem = "<html><font size = 4><b>Erro no banco de dados!</html></b>"; 
            JOptionPane.showMessageDialog(null, mensagem , "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VeiculoViewer");
        setMinimumSize(new java.awt.Dimension(395, 260));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visualizador de Veículos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton2.setText("Remover");
        jButton2.setToolTipText("Remove um veículo");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remover(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 170, 300, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.setToolTipText("Cadastra um veículo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrar(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 50, 300, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Atualizar");
        jButton3.setToolTipText("Atualiza um veículo");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizar(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 130, 300, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Buscar");
        jButton4.setToolTipText("Busca um veículo");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscar(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(40, 90, 300, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 370, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizar
        this.setVisible(false);
        new Atualizar(this, veiculos).setVisible(true);
    }//GEN-LAST:event_atualizar

    private void remover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remover
        this.setVisible(false);
        new Remover(this, veiculos).setVisible(true);
    }//GEN-LAST:event_remover

    private void buscar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscar
        this.setVisible(false);
        new Buscar(this, veiculos).setVisible(true);
    }//GEN-LAST:event_buscar

    private void cadastrar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrar
        this.setVisible(false);
        new Cadastrar(this, veiculos).setVisible(true);
    }//GEN-LAST:event_cadastrar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VeiculoViewer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
